// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using Ioc=WPAppStudio.Ioc;
using IViewModels=WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }
		
		/// <summary>
        /// Resolve a service of type T
        /// </summary>
        /// <typeparam name="T">Type of the service.</typeparam>
        /// <returns></returns>
        public T ResolveService<T>()
        {
            return _container.Resolve<T>();
        }

        /// <summary>
        /// Gets the reference to a Main_NewsViewModel.
        /// </summary>
		public IViewModels.IMain_NewsViewModel Main_NewsViewModel
        {
            get { return _container.Resolve<IViewModels.IMain_NewsViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Videos_DetailVideosViewModel.
        /// </summary>
		public IViewModels.IVideos_DetailVideosViewModel Videos_DetailVideosViewModel
        {
            get { return _container.Resolve<IViewModels.IVideos_DetailVideosViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a EditorialFeed_DetailViewModel.
        /// </summary>
		public IViewModels.IEditorialFeed_DetailViewModel EditorialFeed_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IEditorialFeed_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a GiveawaysFeed_DetailViewModel.
        /// </summary>
		public IViewModels.IGiveawaysFeed_DetailViewModel GiveawaysFeed_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IGiveawaysFeed_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a ReviewsFeed_DetailViewModel.
        /// </summary>
		public IViewModels.IReviewsFeed_DetailViewModel ReviewsFeed_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IReviewsFeed_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a NewsFeed_DetailViewModel.
        /// </summary>
		public IViewModels.INewsFeed_DetailViewModel NewsFeed_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.INewsFeed_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Main_DetailViewModel.
        /// </summary>
		public IViewModels.IMain_DetailViewModel Main_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IMain_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
