// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// EditorialFeed_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IEditorialFeed_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaEditorialFeed_Detail0 property.
        /// </summary>
		bool HasNextpanoramaEditorialFeed_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaEditorialFeed_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaEditorialFeed_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechEditorialFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechEditorialFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareEditorialFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareEditorialFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartEditorialFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartEditorialFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceEditorialFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceEditorialFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaEditorialFeed_Detail0 command.
        /// </summary>
		ICommand NextpanoramaEditorialFeed_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaEditorialFeed_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaEditorialFeed_Detail0 { get; }

	}
}
