// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// GiveawaysFeed_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IGiveawaysFeed_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaGiveawaysFeed_Detail0 property.
        /// </summary>
		bool HasNextpanoramaGiveawaysFeed_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaGiveawaysFeed_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaGiveawaysFeed_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechGiveawaysFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareGiveawaysFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartGiveawaysFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceGiveawaysFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
		ICommand NextpanoramaGiveawaysFeed_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaGiveawaysFeed_Detail0 { get; }

	}
}
