// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Main_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMain_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaMain_Detail0 property.
        /// </summary>
		bool HasNextpanoramaMain_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaMain_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaMain_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechMain_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechMain_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareMain_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareMain_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartMain_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartMain_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceMain_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceMain_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaMain_Detail0 command.
        /// </summary>
		ICommand NextpanoramaMain_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaMain_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaMain_Detail0 { get; }

	}
}
