// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// NewsFeed_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface INewsFeed_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaNewsFeed_Detail0 property.
        /// </summary>
		bool HasNextpanoramaNewsFeed_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaNewsFeed_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaNewsFeed_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechNewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechNewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareNewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareNewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartNewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartNewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceNewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceNewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaNewsFeed_Detail0 command.
        /// </summary>
		ICommand NextpanoramaNewsFeed_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaNewsFeed_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaNewsFeed_Detail0 { get; }

	}
}
