// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// ReviewsFeed_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IReviewsFeed_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaReviewsFeed_Detail0 property.
        /// </summary>
		bool HasNextpanoramaReviewsFeed_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaReviewsFeed_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaReviewsFeed_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechReviewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareReviewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartReviewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceReviewsFeed_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaReviewsFeed_Detail0 command.
        /// </summary>
		ICommand NextpanoramaReviewsFeed_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaReviewsFeed_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaReviewsFeed_Detail0 { get; }

	}
}
