// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of GiveawaysFeed_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class GiveawaysFeed_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IGiveawaysFeed_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.GiveawaysFeed_GiveawaysFeed _giveawaysFeed_GiveawaysFeed;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="GiveawaysFeed_DetailViewModel" /> class.
        /// </summary>
        /// <param name="giveawaysFeed_GiveawaysFeed">The Giveaways Feed_ Giveaways Feed.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public GiveawaysFeed_DetailViewModel(Repositories.GiveawaysFeed_GiveawaysFeed giveawaysFeed_GiveawaysFeed, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_giveawaysFeed_GiveawaysFeed = giveawaysFeed_GiveawaysFeed;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaGiveawaysFeed_Detail0;

        /// <summary>
        /// HasNextpanoramaGiveawaysFeed_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaGiveawaysFeed_Detail0
        {
            get
            {
				return _hasNextpanoramaGiveawaysFeed_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaGiveawaysFeed_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaGiveawaysFeed_Detail0;

        /// <summary>
        /// HasPreviouspanoramaGiveawaysFeed_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaGiveawaysFeed_Detail0
        {
            get
            {
				return _hasPreviouspanoramaGiveawaysFeed_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaGiveawaysFeed_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechGiveawaysFeed_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechGiveawaysFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechGiveawaysFeed_DetailStaticControlCommand
        {
            get { return _textToSpeechGiveawaysFeed_DetailStaticControlCommand = _textToSpeechGiveawaysFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechGiveawaysFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareGiveawaysFeed_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareGiveawaysFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareGiveawaysFeed_DetailStaticControlCommand
        {
            get { return _shareGiveawaysFeed_DetailStaticControlCommand = _shareGiveawaysFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareGiveawaysFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartGiveawaysFeed_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IGiveawaysFeed_DetailViewModel), CreateTileInfoGiveawaysFeed_DetailStaticControl());
        }
		

        private ICommand _pinToStartGiveawaysFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartGiveawaysFeed_DetailStaticControlCommand
        {
            get { return _pinToStartGiveawaysFeed_DetailStaticControlCommand = _pinToStartGiveawaysFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartGiveawaysFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceGiveawaysFeed_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceGiveawaysFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceGiveawaysFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceGiveawaysFeed_DetailStaticControlCommand
        {
            get { return _goToSourceGiveawaysFeed_DetailStaticControlCommand = _goToSourceGiveawaysFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceGiveawaysFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
        public async void NextpanoramaGiveawaysFeed_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _giveawaysFeed_GiveawaysFeed.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaGiveawaysFeed_Detail0;

        /// <summary>
        /// Gets the NextpanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaGiveawaysFeed_Detail0
        {
            get { return _nextpanoramaGiveawaysFeed_Detail0 = _nextpanoramaGiveawaysFeed_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaGiveawaysFeed_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaGiveawaysFeed_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _giveawaysFeed_GiveawaysFeed.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaGiveawaysFeed_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaGiveawaysFeed_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaGiveawaysFeed_Detail0
        {
            get { return _previouspanoramaGiveawaysFeed_Detail0 = _previouspanoramaGiveawaysFeed_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaGiveawaysFeed_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaGiveawaysFeed_Detail0 = await _giveawaysFeed_GiveawaysFeed.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaGiveawaysFeed_Detail0 = await _giveawaysFeed_GiveawaysFeed.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the GiveawaysFeed_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoGiveawaysFeed_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-242457de-80da-42c9-9fbb-98b5451c622c.png"
            };
            return tileInfo;
        }
    }
}
