// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of ReviewsFeed_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class ReviewsFeed_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IReviewsFeed_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.ReviewsFeed_ReviewsFeed _reviewsFeed_ReviewsFeed;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewsFeed_DetailViewModel" /> class.
        /// </summary>
        /// <param name="reviewsFeed_ReviewsFeed">The Reviews Feed_ Reviews Feed.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public ReviewsFeed_DetailViewModel(Repositories.ReviewsFeed_ReviewsFeed reviewsFeed_ReviewsFeed, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_reviewsFeed_ReviewsFeed = reviewsFeed_ReviewsFeed;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaReviewsFeed_Detail0;

        /// <summary>
        /// HasNextpanoramaReviewsFeed_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaReviewsFeed_Detail0
        {
            get
            {
				return _hasNextpanoramaReviewsFeed_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaReviewsFeed_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaReviewsFeed_Detail0;

        /// <summary>
        /// HasPreviouspanoramaReviewsFeed_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaReviewsFeed_Detail0
        {
            get
            {
				return _hasPreviouspanoramaReviewsFeed_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaReviewsFeed_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechReviewsFeed_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechReviewsFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechReviewsFeed_DetailStaticControlCommand
        {
            get { return _textToSpeechReviewsFeed_DetailStaticControlCommand = _textToSpeechReviewsFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechReviewsFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareReviewsFeed_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareReviewsFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareReviewsFeed_DetailStaticControlCommand
        {
            get { return _shareReviewsFeed_DetailStaticControlCommand = _shareReviewsFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareReviewsFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartReviewsFeed_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IReviewsFeed_DetailViewModel), CreateTileInfoReviewsFeed_DetailStaticControl());
        }
		

        private ICommand _pinToStartReviewsFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartReviewsFeed_DetailStaticControlCommand
        {
            get { return _pinToStartReviewsFeed_DetailStaticControlCommand = _pinToStartReviewsFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartReviewsFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceReviewsFeed_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceReviewsFeed_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceReviewsFeed_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceReviewsFeed_DetailStaticControlCommand
        {
            get { return _goToSourceReviewsFeed_DetailStaticControlCommand = _goToSourceReviewsFeed_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceReviewsFeed_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaReviewsFeed_Detail0 command.
        /// </summary>
        public async void NextpanoramaReviewsFeed_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _reviewsFeed_ReviewsFeed.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaReviewsFeed_Detail0;

        /// <summary>
        /// Gets the NextpanoramaReviewsFeed_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaReviewsFeed_Detail0
        {
            get { return _nextpanoramaReviewsFeed_Detail0 = _nextpanoramaReviewsFeed_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaReviewsFeed_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaReviewsFeed_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaReviewsFeed_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _reviewsFeed_ReviewsFeed.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaReviewsFeed_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaReviewsFeed_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaReviewsFeed_Detail0
        {
            get { return _previouspanoramaReviewsFeed_Detail0 = _previouspanoramaReviewsFeed_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaReviewsFeed_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaReviewsFeed_Detail0 = await _reviewsFeed_ReviewsFeed.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaReviewsFeed_Detail0 = await _reviewsFeed_ReviewsFeed.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the ReviewsFeed_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoReviewsFeed_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-242457de-80da-42c9-9fbb-98b5451c622c.png"
            };
            return tileInfo;
        }
    }
}
